name: Build and Test

on:
  push:
    branches:
      - '*'

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: '3.10'

    - name: Configure and build
      run: |
        mkdir -p build
        cd build
        cmake ..
        make -j
        cd ..

    - name: Check for r-type_server and r-type_client
      run: |
        if [ -f r-type_server ] && [ -f r-type_client ]; then
          echo "Both r-type_server and r-type_client exist."
        else
          echo "One or both of r-type_server and r-type_client are missing."
          exit 1
        fi
