name: Documentation

on:
  push:
    branches:
      - "*"

jobs:
  
  
  Documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Doxygen
        run: sudo apt-get install doxygen

      - name: Generate Doxygen Documentation
        run: doxygen Doxyfile

      - name: Put R-TYPE_RFC_V1.txt into documentation
        run: | 
        cp R-TYPE_RFC_V1.txt docs/RFC.txt
        echo "<object data=\"RFC.txt\" width=\"100%\" height=\"100%\"/>" > docs/RFC.html

      - name: Deploy Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs