name: Release

on:
  push:
    branches:
      - main
      - RT-139-File-in-the-releases

jobs:
  CreateReleaseDev:
    runs-on: ubuntu-latest
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "Release"
          prerelease: true
          draft: false
          title: "R-Type v${{ github.run_number }}"
          files: |
            documentation.yml