name: Release

on:
  push:
    branches:
      - main

jobs:
  CreateReleaseDev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "Release"
          prerelease: false
          title: "R-Type v${{ github.run_number }}"