name: Compilation test

on:
  push:
    branches:
      - "*"

env:
  MIRROR_URL: "git@github.com:EpitechPromo2026/B-CPP-500-TLS-5-1-rtype-antonin.laudon.git"

jobs:
  BuildUbuntu:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: BuildLinux
        run: timeout 30m ./install.sh

  BuildWindows:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create PowerShell Profile
        run: New-Item -ItemType File -Path $PROFILE -Force

      - name: Set up MSYS2 environment
        uses: msys2/setup-msys2@v2
        with:
          msys2-root: C:\msys64
          update: true

      - name: Install CMake and g++
        run: |
          $env:Path += ";C:\msys64\usr\bin"
          pacman -S --noconfirm mingw-w64-x86_64-toolchain cmake
    

      - name: BuildWindows
        run: .\install.bat

  MirrorPush:
    runs-on: ubuntu-latest
    needs: BuildUbuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Mirror
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.MIRROR_SSH_PRIVATE_KEY }}

