name: Compilation test

on:
  push:
    branches:
      - '*'

env:
  MIRROR_URL: "git@github.com:EpitechPromo2026/B-CPP-500-TLS-5-1-rtype-antonin.laudon.git"

jobs:

  Build:
    runs-on:
      ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: timeout 10m ./install.sh

  MirrorPush:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Mirror
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.MIRROR_SSH_PRIVATE_KEY }}

  CreateReleaseDev:
    runs-on: ubuntu-latest
    needs: Build
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/RT-99-create-release-of-the-project'

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "Release"
          prerelease: true
          title: "R-Type v${{ github.run_number }}"
